"""
Extract the RGB colour specifications from
ColorBrewer_all_schemes_RGBonly3.csv and write them as lists in
../sahgutils/_color_brewer.py.

"""
import os
import csv

def add_palette(cdict, scheme):
    pal_name = '_%s_cat%s_data' % (scheme[0]['ColorName'],
                                   scheme[0]['NumOfColors'])

    ncolors = int(scheme[0]['NumOfColors'])

    clist = []
    for n in range(ncolors):
        r = int(scheme[n]['R'])/255.0
        g = int(scheme[n]['G'])/255.0
        b = int(scheme[n]['B'])/255.0

        clist.append([r, g, b])

    cdict[pal_name] = clist

if __name__ == '__main__':
    header = """\
# This file was autogenerated from the ColorBrewer palette using the
# script extract_color_brewer_schemes.py found in the tools directory
# of the SAHGutils source distribution. Please see that script for
# further details and don't hand edit this file.


"""

    fin_str = 'Apache-Style Software License for ColorBrewer software and ColorBrewer Color Schemes'

    try:
        fp_in = open('ColorBrewer_all_schemes_RGBonly3.csv')
        reader = csv.DictReader(fp_in)

        cdict = {}
        scheme = []
        for row in reader:
            if (row['ColorName'] == fin_str) and (len(scheme) > 0):
                add_palette(cdict, scheme)
                break
            else:
                if (row['ColorName'] != '') and (len(scheme) > 0):
                    add_palette(cdict, scheme)
                    scheme = []
                    scheme.append(row)
                else:
                    scheme.append(row)

        fp_out = open('../sahgutils/_color_brewer.py', 'w')
        fp_out.write(header)
        fp_out.write('cdict = %s' % cdict)

    finally:
        fp_in.close()
        fp_out.close()
